# Generated by Django 4.0.2 on 2022-02-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemodel',
            old_name='departament',
            new_name='department',
        ),
    ]
