# Generated by Django 4.0.2 on 2022-02-21 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rename_departament_employeemodel_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='document',
            field=models.CharField(default='06872098112', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length must to be 11', regex='^.{11}$')]),
            preserve_default=False,
        ),
    ]
